In [4]:
import torch
import numpy as np
import torch.nn.functional as F

In [5]:
#In-course practise

#1.1.7 create a 2-D tensor x with ones on the diagonal and zeros elsewhere (shape:[4,5],dype=double) 
x = torch.eye(4,5,dtype=torch.float64)
print(x,x.type())



tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], dtype=torch.float64) torch.DoubleTensor


In [6]:
#1.1.8 get the 0-th diagonal of x, and calculate the sum and convert its dtype to int
x = torch.diag(x,0)
print(x)
x = x.sum()
print(x)


tensor([1., 1., 1., 1.], dtype=torch.float64)
tensor(4., dtype=torch.float64)


In [14]:


#1.2.6 Apply a 2D convolution over an input followed by a linear transformation

# create a random input tensor with shape [2,3,5,5]
x = torch.randn(2,3,5,5)
print('input :',x.shape)
# create a random filter with shape [4,3,3,3]
conv_w = torch.randn(4,3,3,3)
print('filter:',conv_w.shape)
# perform 2d convolution
conv_out = F.conv2d(x,conv_w)
print('conv_out:',conv_out.shape)

# create a random weight matrix so that the output shape is [3,5]
conv_out = conv_out.view(2,-1)
print('conv_out:',conv_out.shape)
linear_w = torch.randn(5,conv_out.shape[1])
print('linear_w:',linear_w.shape)
linear_out = F.linear(conv_out,linear_w,bias=None)
print('linear_out:',linear_out.shape)


input : torch.Size([2, 3, 5, 5])
filter: torch.Size([4, 3, 3, 3])
conv_out: torch.Size([2, 4, 3, 3])
conv_out: torch.Size([2, 36])
linear_w: torch.Size([5, 36])
linear_out: torch.Size([2, 5])


In [15]:
x = torch.randn(2,2,2,2,2)

In [16]:
print(x.size())

torch.Size([2, 2, 2, 2, 2])


In [17]:
x.view(-1)

tensor([-0.6140,  1.5316, -0.7093, -1.3144, -0.1790,  0.4069, -0.5434, -0.0996,
        -0.5497,  0.3227, -0.2206, -0.5074,  0.6792,  0.8326,  1.0295, -0.4901,
        -0.5959, -0.0237, -0.0720,  1.7825, -1.2991,  0.4773,  0.2830, -1.5192,
        -0.3015,  0.3725, -0.0751, -1.3654, -2.4126, -0.5090,  1.5371, -0.7187])

In [18]:
x.view(1,-1)

tensor([[-0.6140,  1.5316, -0.7093, -1.3144, -0.1790,  0.4069, -0.5434, -0.0996,
         -0.5497,  0.3227, -0.2206, -0.5074,  0.6792,  0.8326,  1.0295, -0.4901,
         -0.5959, -0.0237, -0.0720,  1.7825, -1.2991,  0.4773,  0.2830, -1.5192,
         -0.3015,  0.3725, -0.0751, -1.3654, -2.4126, -0.5090,  1.5371, -0.7187]])

In [20]:
print(x.view(1,-1).size())

torch.Size([1, 32])
