In [1]:
import torch
import numpy as np
import torch.nn.functional as F

#1.2 Use basic operations from PyTorch Docs (https://pytorch.org/docs/stable/torch.html)

#1.2.1 concatenate two tensors and save the result to a local file
x1 = torch.tensor([1,2,3])
x2 = torch.tensor([4,5,6])
x = torch.cat((x1,x2))
print(x)
torch.save(x,'x.pt')








#torch.randn(2, 3)

#torch.save(model, 'model.pt')

#torch.set_num_threads(2)

#with torch.no_grad():
    
#torch.sqrt(x)

#F.conv2d(x, w)

#F.max_pool1d(x, kernel_size=3, stride=2)

#F.relu(x)

#F.batch_norm(x, running_mean, running_var)

#F.linear(x, w)

#F.dropout(x)

#F.one_hot(torch.arange(0,5))

#F.cosine_similarity(x1, x2)

#F.cross_entropy(x, y)
#F.upsample(x,size=[16,16])

#torch.nn.parallel.data_parallel(module, x)

#nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')

tensor([1, 2, 3, 4, 5, 6])


In [2]:
#1.2.2 read tensor data from a local file, convert it to float dtype and then calculate its square root
x = torch.load('x.pt')
print(x)
x = x.float()
print(x)
x = torch.sqrt(x)
print(x)


tensor([1, 2, 3, 4, 5, 6])
tensor([1., 2., 3., 4., 5., 6.])
tensor([1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495])


In [3]:
#1.2.3 Apply a 2D convolution over an input and upsample the result
x = torch.ones(5,5)
w = torch.eye(3,3)
print('input:',x)
print('filter:',w)

print(x.shape,w.shape)

x = x.view(1,1,5,5)
w = w.view(1,1,3,3)
print(x.shape,w.shape)

conv = F.conv2d(x,w)
print(conv)

up_conv = F.interpolate(conv,size=[5,5])
print(up_conv)

input: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
filter: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([5, 5]) torch.Size([3, 3])
torch.Size([1, 1, 5, 5]) torch.Size([1, 1, 3, 3])
tensor([[[[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]]])
tensor([[[[3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.],
          [3., 3., 3., 3., 3.]]]])


In [4]:
#1.2.4 Apply a linear transformation to the input and then apply a logsigmoid activation to the result

x = torch.ones(1,10)
w = torch.rand(2,10)
print(x,x.shape)
print(w,w.shape)
y = F.linear(x,w,bias=None)
print(y)
y = F.logsigmoid(y)
print(y)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]) torch.Size([1, 10])
tensor([[2.6584e-01, 1.3295e-01, 8.7302e-01, 6.5517e-04, 6.8876e-02, 9.1124e-01,
         3.6529e-01, 3.9072e-01, 4.1773e-01, 1.9793e-01],
        [5.4180e-01, 8.0033e-01, 2.0021e-01, 1.4854e-01, 9.0201e-01, 4.7689e-01,
         6.0182e-01, 6.6357e-01, 9.6789e-01, 4.6710e-01]]) torch.Size([2, 10])
tensor([[3.6242, 5.7702]])
tensor([[-0.0263, -0.0031]])


In [54]:
#1.2.5 Compute the cross-entropy loss

# two samples with label from one of the 4 classes (0,1,2,3)
x = torch.randn(2,4)
y = torch.randint(4,(2,))
print('x:',x)
print('y:',y)
loss = F.cross_entropy(x,y)
print('loss:',loss)

x: tensor([[ 1.5814, -0.5423, -0.8403, -0.6419],
        [ 0.4298,  1.0529, -1.3988, -0.3651]])
y: tensor([3, 0])
loss: tensor(1.8722)


In [67]:
#1.2.6 Apply a 2D convolution over an input followed by a linear transformation

# create a random input tensor with shape [2,3,5,5]

# create a random filter with shape [4,3,3,3]

# perform 2d convolution

# create a random weight matrix so that the output shape is [3,5]

# perform linear transformation


input : torch.Size([2, 3, 5, 5])
filter: torch.Size([3, 3, 3, 3])
conv_out: torch.Size([2, 3, 3, 3])
conv_out: torch.Size([3, 18])
linear_w: torch.Size([5, 18])
linear_out: torch.Size([3, 5])
