In [2]:
# import python packages 
import numpy as np
import torch


In [3]:
#1.1 Construct a tensor (https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)

#1.1.1 construct a tensor from a numpy array
np_array = np.array([1,2,3,4])
print(type(np_array))
tensor_array = torch.tensor(np_array)
print(type(tensor_array))
print(np_array,tensor_array)


<class 'numpy.ndarray'>
<class 'torch.Tensor'>
[1 2 3 4] tensor([1, 2, 3, 4])


In [4]:
#1.1.2 construct a random tensor of shape [2,3]

rand_tensor = torch.rand([2,3],dtype=torch.float64,device=torch.device('cpu:0'),requires_grad=True)
print(rand_tensor,rand_tensor.type())


tensor([[0.2201, 0.0705, 0.8851],
        [0.3819, 0.1598, 0.8348]], dtype=torch.float64, requires_grad=True) torch.DoubleTensor


In [5]:
#1.1.3 Built-in functions in the tensor class (https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

x = torch.rand([2,3]) # a tensor

#1.1.4 check the size of x
print(x.size())


torch.Size([2, 3])


In [6]:

#1.1.5 convert a tensor to a numpy array
x_array = x.numpy()
print(x_array,type(x_array))


[[0.13248688 0.093409   0.20983249]
 [0.6609338  0.61761826 0.31949747]] <class 'numpy.ndarray'>


In [7]:

#1.1.6 get the maximum value of x
print(x.max())



tensor(0.6609)


In [24]:
# In-course practise

#1.1.7 create a 2-D tensor x with ones on the diagonal and zeros elsewhere (shape:[4,5],dype=double) 


In [25]:
#1.1.8 get the 0-th diagonal of x, and calculate the sum and convert its dtype to int
