In [3]:
import torch
import numpy as np

x1 = torch.ones(2,2)

In [4]:
print(x1)

tensor([[1., 1.],
        [1., 1.]])


In [5]:
print(x1.grad)

None


In [6]:
x2 = torch.ones(2,2,requires_grad=True)

In [7]:
print(x2,x2.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None


In [8]:
x1_sum = x1 + x1
print(x1_sum.grad_fn)
print(x1_sum.grad)
out1 = x1_sum.mean()
print(out1.grad_fn)
print(out1.grad)

None
None
None
None


In [9]:
x2_sum = x1 + x2
out2 = x2_sum.mean()
print(y2.grad_fn)
print(y2.grad)
#y2 = y2.mean()
#print(y2.grad_fn)
#print(y2.grad)

NameError: name 'y2' is not defined

In [10]:
#x1.backward()

In [11]:
out2.backward()
print(x2.grad,x1.grad)


tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]]) None


In [12]:
out2


tensor(2., grad_fn=<MeanBackward0>)

In [13]:
x2_sum

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [14]:
a = torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)

In [15]:
b = torch.mean(a)

In [16]:
print(a,b)

tensor([1., 2., 3., 4.], requires_grad=True) tensor(2.5000, grad_fn=<MeanBackward0>)


In [17]:
print(a.grad,a.grad_fn,a.requires_grad)

None None True


In [18]:
print(b.grad,b.grad_fn,b.requires_grad)

None <MeanBackward0 object at 0x1243661d0> True


In [19]:
#b.backward()

In [20]:
print(b.grad,b.grad_fn,b.requires_grad)

None <MeanBackward0 object at 0x1243665f8> True


In [21]:
print(a.grad,a.grad_fn,a.requires_grad)
print(b.grad,b.grad_fn,b.requires_grad)

None None True
None <MeanBackward0 object at 0x124366978> True


In [22]:
c=torch.pow(b,2)

In [23]:
print(c.grad,c.grad_fn,c.requires_grad)
print(b.grad,b.grad_fn,b.requires_grad)

None <PowBackward0 object at 0x124366e48> True
None <MeanBackward0 object at 0x124366e10> True


In [24]:
print(c)

tensor(6.2500, grad_fn=<PowBackward0>)


In [25]:
print(a.grad,a.grad_fn,a.requires_grad)

None None True


In [26]:
c.backward()

In [27]:
print(a.grad,a.grad_fn,a.requires_grad)


tensor([1.2500, 1.2500, 1.2500, 1.2500]) None True


In [28]:
print(b.grad,b.grad_fn,b.requires_grad)

None <MeanBackward0 object at 0x12436d6a0> True


In [29]:
print(c.grad,c.grad_fn,c.requires_grad)

None <PowBackward0 object at 0x12436d940> True


In [30]:
print(a.is_leaf,b.is_leaf,c.is_leaf)

True False False


In [189]:
type(a)

torch.Tensor

In [190]:
type(b)

torch.Tensor