In [60]:
import torch
import numpy as np

x1 = torch.ones(2,2)

In [61]:
print(x1)

tensor([[1., 1.],
        [1., 1.]])


In [62]:
print(x1.grad)

None


In [83]:
x2 = torch.ones(2,2,requires_grad=True)

In [84]:
print(x2,x2.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None


In [85]:
x1 = x1 + x1
print(x1.grad_fn)
print(x1.grad)
x1 = x1.mean()
print(x1.grad_fn)
print(x1.grad)

None
None
None
None


In [86]:
x_sum = x2 + x2
y2 = x_sum.mean()
print(y2.grad_fn)
print(y2.grad)
#y2 = y2.mean()
#print(y2.grad_fn)
#print(y2.grad)

None


In [87]:
#x1.backward()

In [88]:
y2.backward()
print(y2.grad_fn)
print(y2.grad)

None


In [89]:
print(x2.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [ ]:
print()